# Generated by Django 4.2.1 on 2023-05-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_block_glav_resens_roman_sobit_stix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glav',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
