# Generated by Django 4.2.1 on 2023-05-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_glav_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resens',
            old_name='resens_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='sobit',
            old_name='sobit_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='stix',
            old_name='text_stix',
            new_name='stix',
        ),
        migrations.AddField(
            model_name='block',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AddField(
            model_name='resens',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AddField(
            model_name='roman',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AddField(
            model_name='sobit',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AddField(
            model_name='stix',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
